# Generated by Django 5.1 on 2024-08-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
