# Generated by Django 5.1 on 2024-08-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='evaluations_made',
            field=models.IntegerField(default=0),
        ),
    ]
